### ISSUE TITLE
Learn form You！！！

### ISSUE THREAD

**Issue by HaixingOoO** [li-jia-nan/Learning-notes#1]
您好，可以的话我想把你的笔记记录到我的个人博客吗？会标明出处的😊😊😊

**Comment by li-jia-nan** [comment]
> 您好，可以的话我想把你的笔记记录到我的个人博客吗？会标明出处的😊😊😊

可以的，但是有两个点哈：

- 出处要标在明显的地方
- 博客内容不可以随便改

感谢支持

**Comment by HaixingOoO** [comment]
> 可以的，但是有两个点哈：
> 
> * 出处要标在明显的地方
> * 博客内容不可以随便改
> 
> 感谢支持

嗯，然后这个博客内容不可以随便改的意思，是说不能乱改的你的笔记内容吗？但是你的笔记说的一些不关技术的内容我是否可以去掉？

**Comment by li-jia-nan** [comment]
> 不关技术的内容

不关技术的内容指的是什么东西呢？

**Comment by HaixingOoO** [comment]
> > 不关技术的内容
> 
> 不关技术的内容指的是什么东西呢？

![IMG_0094](https://github.com/li-jia-nan/Learning-notes/assets/65376724/eb1ed7e5-4cb2-41a6-b194-cd5de157ddc2)
* 比如`难点`下面那段吐槽😂😂😂

**Comment by li-jia-nan** [comment]
噗，可以的，你看着改就行

**Comment by HaixingOoO** [comment]
> 噗，可以的，你看着改就行

ok
